# Example Site settings

google_analytics: G-5DRD1VR5JX

header_pages:
  - index.md
  - about.md
 # - gallery.md
  - Joe.md
  - books.md

footer: 'ta mig tillbaka till <a href="https://ronim-efrin.github.io">links-sidan</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
